-- Габариты и вес для карточек WB
ALTER TABLE "WbCard" ADD COLUMN "weightKg" DOUBLE PRECISION;
ALTER TABLE "WbCard" ADD COLUMN "heightCm" DOUBLE PRECISION;
ALTER TABLE "WbCard" ADD COLUMN "widthCm" DOUBLE PRECISION;
ALTER TABLE "WbCard" ADD COLUMN "depthCm" DOUBLE PRECISION;
